export enum Skills {
    "Acrobaties",
    "Art de la magie",
    "Artisanat",
    "Bluff",
    "Concentration",
    "Connaissances",
    "Contrefaçon",
    "Crochetage",
    "Décryptage",
    "Déguisement",
    "Déplacement silencieux",
    "Désamorçage/Sabotage",
    "Détection",
    "Diplomatie",
    "Discrétion",
    "Dressage",
    "Equilibre",
    "Equitation",
    "Escalade",
    "Escamotage",
    "Estimation",
    "Evasion",
    "Fouille",
    "Intimidation",
    "Maîtrise des cordes",
    "Natation",
    "Perception auditive",
    "Premiers secours",
    "Profession",
    "Psychologie",
    "Renseignements",
    "Représentation",
    "Saut",
    "Survie",
    "Utilisation d'objets magiques",
}